server:
  port: 8080
spring:
  application:
    name: funnyutils  # 应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://43.163.122.239:3306/funnyutils?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
    username: funnyutils
  redis:
    host: 43.163.122.239
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#日志级别配置
logging:
  level:
    root: info
    com.zach.funnyutils: info
    com.alibaba.nacos.client.naming: warn
    com.alibaba.nacos.client.config: warn